### ISSUE TITLE
Week 05 Day 2 - Function Junction

### ISSUE THREAD

**Issue by gstark** [JOLee83/assignments#17]
## Objectives

After completing this assignment, you should be able to:

- Demonstrate understanding of types, functions, argument-handling, loops, and conditional statements

## Requirements

1.  Fork [this repository](https://github.com/suncoast-devs/function-junction) to your own account.
2.  Change into your training directory
3.  Clone your repository: `hub clone function-junction`
4.  Change into your project's directory: `cd function-junction`
5.  Install the dependencies: `yarn install` (or just `yarn` for short)
6.  Open in Code: `code .`
7.  Start the test runner: `yarn test`
8.  Open `src/functions.test.js` and work on functions until tests pass.
9.  Commit and push your work to GitHub.
10. Turn in the URL to your GitHub repo.

### Explorer Mode

- [ ] All tests passing
- [ ] No linter warnings
- [ ] Turn in the homework using the URL to your repository on Github.

### Adventure Mode

- [ ] If you used "built-in" JavaScript methods like `String.reverse()` or `Array.max()` to solve these problems, try implementing them from scratch.
- [ ] Vice-versa: if you implemented your solutions from scratch, look in the documentation linked below to see if JavaScript has any built-in functions to help solve these problems.

### Epic Mode

- [ ] Expand the `sum` and `max` functions to take arrays instead of numbers and update the tests so they pass.
- [ ] Create your own simple functions with tests.
- [ ] Anytime in your code that you used a `for` loop or a `while` loop, convert it to use a `map`, `filter` or `reduce`.

## Additional Resources

Reference the documentation on MDN to find what kind of helpful functions might already be on `Array` and `String` in JavaScript.

- [String Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String).
- [Array Functions on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array).

**Comment by JOLee83** [comment]
https://github.com/JOLee83/function-junction.git

**Comment by gstark** [comment]
Good work

for `sumOfArray` see if you can use one of the iterating functions.


```function isVowel(x) {
	if (
		x === 'a' ||
		x === 'A' ||
		x === 'e' ||
		x === 'E' ||
		x === 'i' ||
		x === 'I' ||
		x === 'o' ||
		x === 'O' ||
		x === 'u' ||
		x === 'U'
	) {
		return true
	} else {
		return false
	}
}
```

can be

```
function isVowel(x) {
	return (
		x === 'a' ||
		x === 'A' ||
		x === 'e' ||
		x === 'E' ||
		x === 'i' ||
		x === 'I' ||
		x === 'o' ||
		x === 'O' ||
		x === 'u' ||
		x === 'U'
	)
}
```

since

```
if (condition) {
  return true
} else {
  return false
}
```

is the same as

```
return (condition)
```

Do you understand how `!!~'aeiou'.indexOf(letter)` works? We haven't covered this in class so I want to make sure you understand the idiom if you are going to use it.

```
function reverse(x) {
	let x2 = x.split('')
	let x3 = x2.reverse()
	let x4 = x3.join('')
	return x4
}
```

You don't need all those temp variables. you can just do `x.split('').reverse().join('')`

also try to use more expressive variable names than `x` or `a` and `b`

**Comment by gstark** [comment]
Your homework is: Meets Expectations

![Awesome Work!](https://media1.giphy.com/media/PoCC07KoJ3tFtUyOaY/200w_d.gif)
