### ISSUE TITLE
Week 06 Day 2 - Do you want to build a Snowman?

### ISSUE THREAD

**Issue by ambethia** [JOLee83/assignments#22]
## Do you want to build a Snowman?

In this assignment, you'll build a _less grim_ variation of a popular game:

![Snowman](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/front-end/react-ii/assignments/assets/snowman.gif)

## Objectives

- Reinforce component architecture in React
- Effective use of props and state in React

## Requirements

**Work in groups of 2 or 3 for this project.** You should turn in 1 repository that contains commits from each team member.

We're going to build a sort of _reverse_ hangman. The player can't lose; they just get to build a snowman by adding parts each time they guess a letter **correctly**.
You will need to download these files and add them to your project:

1.  [Word List](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/front-end/react-ii/assignments/assets/words.json)
2.  [Snowman Images](https://raw.githubusercontent.com/suncoast-devs/handbook/master/curriculum/front-end/react-ii/assignments/assets/snowman.zip) (Unzip these before adding to your project)

### Explorer Mode

- [x] Selects a random word from the list and display a number of blank spaces (or underscores) equal to the word length.
- [x] Display a list of letters, A through Z as clickable buttons.
- [x] When the player guesses a letter (clicks the button):
  - [x] All instances of that letter are revealed at their corresponding positions in the word.
  - [x] The button becomes disabled, as it has already been guessed.
  - [x] Display the snowman image that corresponds with the number of letters revealed in the word.

### Adventure Mode

- [x] After the word has been completed, offer the player to play again. Reset the state of the game without a page reload.

### Epic Mode

Refactor the game to play like a traditional "hangman" game:

- [ ] If the chosen letter is _not_ part of the word, the snowman "grows"; increase a counter by one for each incorrect guess.
- [ ] If the snowman is completed (counter reaches 7) before the word is completed, the player loses, and the snowman wins.

**Comment by JOLee83** [comment]
https://github.com/AllanSeitz/snowman.git
https://snow-man-justin-allan.surge.sh

**Comment by gstark** [comment]
Your homework was marked: **Meets Expectations**

![With LASERS](https://gifs.suncoast.io/rails/active_storage/blobs/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBGdz09IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--8de0b77cb9bd24d453ed6e604c00bc8768a57d5c/BriskEnviousGraywolf.gif)
> &ldquo;With LASERS&rdquo;
__&mdash; via **[Jason L Perry](https://gifs.suncoast.io/venerations/13)**__
