### ISSUE TITLE
Week 07 Day 4 - Wireframes

### ISSUE THREAD

**Issue by gstark** [JOLee83/assignments#26]
## Build wireframes of your Capstone Project

# Be prepared to show these to your instructor early next week.

**Comment by JOLee83** [comment]
![screenshot 48](https://user-images.githubusercontent.com/42788255/47259354-940e6180-d476-11e8-99fd-78267de77c24.png)
![screenshot 49](https://user-images.githubusercontent.com/42788255/47259355-940e6180-d476-11e8-896f-54703ccdd029.png)
![screenshot 50](https://user-images.githubusercontent.com/42788255/47259356-940e6180-d476-11e8-86a9-ac7de922c6f7.png)
![screenshot 52](https://user-images.githubusercontent.com/42788255/47259357-940e6180-d476-11e8-88b7-b9e01d9d4202.png)
![screenshot 53](https://user-images.githubusercontent.com/42788255/47259358-940e6180-d476-11e8-8c4b-be58f457ebae.png)
![screenshot 54](https://user-images.githubusercontent.com/42788255/47259359-94a6f800-d476-11e8-8d16-f63b92d75135.png)
